### ISSUE TITLE
Add themes

### ISSUE THREAD

**Issue by pavlovt** [shakee93/toastedjs#1]
Hi,
Is it possible to define custom themes and add them through the configuration when creating the notification?

**Comment by shakee93** [comment]
take a look at the themes dir and make a theme. and import it to your project.
[themes dir](https://github.com/shakee93/toastedjs/tree/master/src/sass/themes)

when initializing the notification set the theme's class name on

```javascript
{
    theme : 'your_theme_name'
}
```

**Comment by pavlovt** [comment]
This is great, thanks!
